image: "node:latest"

stages:
  - build
  - deploy

build-production:
  stage: build
  only:
    - master
  artifacts:
    paths:
      - front/build
  script:
    - cd front
    - yarn install
    - yarn build

deploy-production:
  stage: deploy
  only:
    - master
  script:
    - npm i -g firebase-tools
    - cd back 
    - firebase deploy --token $FIREBASE_TOKEN
