name: production

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: cd front
      - run: yarn install
      - run: yarn build

  deploy:
    runs-on: ubuntu-latest
    shell: bash
    needs: build
    steps:
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i -g firebase-tools
      - run: cd back/functions
      - run: npm install
      - run: cd ..
      - run: firebase deploy --token "$FIREBASE_TOKEN"
