name: production

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          cd front
          yarn install
          yarn build
      - uses: actions/upload-artifact@v1
        with:
          name: front/build
          path: front/build
          

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/download-artifact@v1
        with:
          name: front/build
      - run: npm i -g firebase-tools
      - run: | 
          cd back/functions
          npm install
      - run: |
          cd back
          firebase deploy --token "$FIREBASE_TOKEN"
