name: production

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - cd front
      - yarn install
      - yarn build

  deploy:
    runs-on: ubuntu-latest
    shell: bash
    needs: build
    steps:
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - npm i -g firebase-tools
      - cd back/functions
      - npm install
      - cd ..
      - firebase deploy --token "$FIREBASE_TOKEN"
